In [26]:
import pandas as pd

# Read CSV
df_raw = pd.read_csv("csv_pny/psam_p36.csv", dtype=str)
df_raw

,RT,SERIALNO,DIVISION,SPORDER,PUMA,REGION,STATE,ADJINC,PWGTP,AGEP,...,PWGTP71,PWGTP72,PWGTP73,PWGTP74,PWGTP75,PWGTP76,PWGTP77,PWGTP78,PWGTP79,PWGTP80
0,P,2023GQ0000006,2,01,04109,1,36,1019518,78,19,...,11,11,203,77,159,67,89,141,74,73
1,P,2023GQ0000012,2,01,03208,1,36,1019518,30,41,...,32,30,29,32,28,27,31,32,29,28
2,P,2023GQ0000015,2,01,00901,1,36,1019518,6,66,...,6,4,4,4,6,6,6,5,6,6
3,P,2023GQ0000016,2,01,01204,1,36,1019518,58,56,...,59,60,58,59,60,56,56,60,58,57
4,P,2023GQ0000049,2,01,00703,1,36,1019518,70,91,...,70,70,68,68,71,69,68,71,68,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206403,P,2023HU1459885,2,04,04503,1,36,1019518,36,61,...,9,14,40,40,63,63,11,40,37,12
206404,P,2023HU1459885,2,05,04503,1,36,1019518,50,60,...,13,15,50,58,87,76,13,50,47,16
206405,P,2023HU1459895,2,01,02201,1,36,1019518,112,28,...,161,28,94,35,118,101,116,33,41,25
206406,P,2023HU1459895,2,02,02201,1,36,1019518,25,4,...,40,8,28,11,32,24,20,10,6,8
206407,P,2023HU1459895,2,03,02201,1,36,1019518,53,27,...,126,16,52,17,52,48,50,16,19,17

In [27]:
# Create Subset
cols = [
    # IDs / meta (not features later, just for reference)
    "SERIALNO", "SPORDER", "PWGTP",

    # target + coverage detail (HINS*, PRIVCOV/PUBCOV used only for sanity, not as features)
    "HICOV", "HINS1", "HINS2", "HINS3", "HINS4", "HINS5", "HINS6", "HINS7",
    "PRIVCOV", "PUBCOV",
    
    # GROUP 1: Income & Affordability
    "WAGP", "POVPIP", "SEMP", "INTP", "RETP", "SSP", "SSIP", "PAP", #"PINCP",

    # GROUP 2: Employment Quality
    "ESR", "COW", "WKL", "OCCP", "INDP",

    # GROUP 3: Demographics & Life Stage
    "AGEP", "SEX", "MAR", "MIG", "NATIVITY", "RAC1P", "HISP", #"CIT",

    # GROUP 4: Education
    "SCHL", "SCH",

    # GROUP 5: Health & Disability
    "DIS", "DEAR", "DEYE", "DPHY",

    # GROUP 6: Geography
    "STATE", "PUMA", "REGION", "DIVISION",
]

df_subset = df_raw[cols].copy()

df_subset.head(20)

,SERIALNO,SPORDER,PWGTP,HICOV,HINS1,HINS2,HINS3,HINS4,HINS5,HINS6,...,SCHL,SCH,DIS,DEAR,DEYE,DPHY,STATE,PUMA,REGION,DIVISION
0,2023GQ0000006,01,78,1,1,1,2,2,2,2,...,19,3,2,2,2,2,36,04109,1,2
1,2023GQ0000012,01,30,1,2,2,2,1,2,2,...,16,1,1,2,2,2,36,03208,1,2
2,2023GQ0000015,01,6,1,2,2,1,1,2,2,...,01,1,1,2,2,2,36,00901,1,2
3,2023GQ0000016,01,58,1,2,2,2,1,2,2,...,14,1,1,2,2,1,36,01204,1,2
4,2023GQ0000049,01,70,1,2,2,1,2,2,2,...,22,1,1,2,2,1,36,00703,1,2
5,2023GQ0000060,01,77,1,2,2,2,1,2,2,...,18,3,1,2,2,2,36,00402,1,2
6,2023GQ0000062,01,4,1,2,2,2,1,2,2,...,17,1,1,2,2,2,36,03002,1,2
7,2023GQ0000090,01,20,1,2,2,1,2,2,2,...,13,1,2,2,2,2,36,00200,1,2
8,2023GQ0000092,01,61,1,1,2,2,2,2,2,...,16,3,2,2,2,2,36,03206,1,2
9,2023GQ0000095,01,24,1,2,1,2,2,2,2,...,16,2,1,2,2,2,36,00100,1,2
10,2023GQ0000136,01,63,1,2,1,2,2,2,2,...,19,3,2,2,2,2,36,04165,1,2
11,2023GQ0000140,01,48,1,2,2,2,1,2,2,...,16,1,1,2,2,1,36,00403,1,2
12,2023GQ0000145,01,17,1,1,2,2,2,2,2,...,16,3,2,2,2,2,36,01300,1,2
13,2023GQ0000160,01,12,1,2,2,2,1,2,2,...,17,1,1,2,2,2,36,03313,1,2
14,2023GQ0000174,01,71,1,2,1,2,2,2,2,...,16,2,2,2,2,2,36,03102,1,2
15,2023GQ0000188,01,54,1,2,2,1,1,2,2,...,19,1,1,2,2,1,36,00100,1,2
16,2023GQ0000217,01,63,1,2,2,2,1,2,2,...,11,1,2,2,2,2,36,02803,1,2
17,2023GQ0000221,01,54,1,1,2,2,2,2,2,...,19,3,1,2,2,2,36,03114,1,2
18,2023GQ0000235,01,5,1,2,2,2,1,2,2,...,12,2,1,2,2,2,36,03209,1,2
19,2023GQ0000265,01,73,1,1,2,2,2,2,2,...,19,3,2,2,2,2,36,00701,1,2

In [18]:
na_summary = (
    df_subset.isna()
    .sum()
    .to_frame("na_count")
    .assign(na_pct=lambda x: x["na_count"] / len(df_subset))
)

print(na_summary)

          na_count    na_pct
SERIALNO         0  0.000000
SPORDER          0  0.000000
PWGTP            0  0.000000
HICOV            0  0.000000
HINS1            0  0.000000
HINS2            0  0.000000
HINS3            0  0.000000
HINS4            0  0.000000
HINS5            0  0.000000
HINS6            0  0.000000
HINS7            0  0.000000
PRIVCOV          0  0.000000
PUBCOV           0  0.000000
WAGP         29121  0.141085
POVPIP        9838  0.047663
SEMP         29121  0.141085
INTP         29121  0.141085
RETP         29121  0.141085
SSP          29121  0.141085
SSIP         29121  0.141085
PAP          29121  0.141085
ESR          31428  0.152262
COW          83115  0.402673
WKL          31428  0.152262
OCCP         83115  0.402673
INDP         83115  0.402673
AGEP             0  0.000000
SEX              0  0.000000
MAR              0  0.000000
MIG           1717  0.008318
NATIVITY         0  0.000000
RAC1P            0  0.000000
HISP             0  0.000000
SCHL          5178  0.025086
SCH           5178  0.025086
DIS              0  0.000000
DEAR             0  0.000000
DEYE             0  0.000000
DPHY          8815  0.042707
STATE            0  0.000000
PUMA             0  0.000000
REGION           0  0.000000
DIVISION         0  0.000000

In [25]:
# Identify columns with at least one NA
cols_with_na = na_summary.query("na_count > 0").index.tolist()

# Create subset with only those columns
df_with_na = df_subset[cols_with_na].copy()

df_with_na.head(50)

df_with_na.to_csv("df_with_na_columns.csv", index=False)